<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1 plus MathML 2.0//EN"
        "http://www.w3.org/Math/DTD/mathml2/xhtml-math11-f.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>Example of MathML embedded in an XHTML file</title>
    <meta name="description" content="Example of MathML embedded in an XHTML file"/>
</head>
<body>
<math mode="display" xmlns="http://www.w3.org/1998/Math/MathML">
    <semantics>
        <mrow>
            <mi>x</mi>
            <mo>=</mo>
            <mfrac>
                <mrow>
                    <mo form="prefix">&minus;</mo>
                    <mi>b</mi>
                    <mo>&pm;</mo>
                    <msqrt>
                        <msup>
                            <mi>b</mi>
                            <mn>2</mn>
                        </msup>
                        <mo>&minus;</mo>
                        <mn>4</mn>
                        <mo>&it;</mo>
                        <mi>a</mi>
                        <mo>&it;</mo>
                        <mi>c</mi>
                    </msqrt>
                </mrow>
                <mrow>
                    <mn>2</mn>
                    <mo>&it;</mo>
                    <mi>a</mi>
                </mrow>
            </mfrac>
        </mrow>
        <annotation encoding="application/x-tex"><!-- TeX -->
            x = \frac{-b\pm\sqrt{b^2-4ac}}{2a}
        </annotation>
        <annotation encoding="StarMath 5.0">
            x = {-b plusminus sqrt {b^2 - 4 ac}} over {2 a}
        </annotation>
        <!-- More annotations can be written: application/x-troff-eqn for eqn, application/x-asciimath for AsciiMath... -->
        <!-- Semantic MathML go under <annotation-xml encoding="MathML-Content">. -->
    </semantics>
</math>
</body>
</html>