<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Alice's Adventures in Wonderland -- Chapter I</title>
    <style>
        @page {
            size: 4.18in 6.88in;
            margin: 0.25in;
            -fs-flow-top: "header";
            -fs-flow-bottom: "footer";
            -fs-flow-left: "left";
            -fs-flow-right: "right";
            border: thin solid black;
            padding: 1em;
        }

        #header {
            font-weight: bold;
            font-family: serif;
            position: absolute; top: 0; left: 0;
            -fs-move-to-flow: "header";
        }

        #footer {
            font-size: 90%; font-style: italic;
            position: absolute; bottom: 0; left: 0;
            -fs-move-to-flow: "footer";
        }


        #pagenumber:before {
            content: counter(page);
        }

        #pagecount:before {
            content: counter(pages);
        }
    </style>
</head>

<body>
<div id="header" style="">Alice's Adventures in Wonderland</div>
<div id="footer" style="">  Page <span id="pagenumber"/> of <span id="pagecount"/> </div>

<h1>CHAPTER I</h1>

<h2>Down the Rabbit-Hole</h2>

<p class="dropcap-holder">
<span class="dropcap">A</span>lice was beginning to get very tired of
sitting by her sister on the bank, and of having nothing to do: once or
twice she had peeped into the book her sister was reading, but it had
no pictures or conversations in it, `and what is the use of a book,'
thought Alice `without pictures or conversation?'
</p>

<p>So she was considering in her own mind (as well as she could,
    for the hot day made her feel very sleepy and stupid), whether the
    pleasure of making a daisy-chain would be worth the trouble of
    getting up and picking the daisies, when suddenly a White Rabbit
    with pink eyes ran close by her. </p>

<p class="figure">
    <img src="${alice2}" width="200px" height="300px" alt=""/>
    <br/>
    <b>White Rabbit checking watch</b>
</p>
</body>
</html>